# Numpy

+ Numericial Python
+ 파이썬 고성능 과학 계산용 패키지 
+ 일반 List에 비해 빠르고, 메모리 효율적 
+ 반복문 없이 데이터 배열에 대한 처리 지원 
+ 배열(ndarray, n dimension array)
+ 연속된 메모리 구조, 동작속도가 빠르다, comma를 사용하지 않고 공백으로 요소구별, 오직 한 가지 타입만 갖을 수 있다

### ndarray 생성 

In [19]:
import numpy as np
# ndarray  : n dimension array
a = np.array([0,1,2,3,4,5])
print(a)
print(type(a))
print(a.dtype)  # 요소의 타입이 모두 동일, windows:int32, mac/linux:int64
a  

[0 1 2 3 4 5]
<class 'numpy.ndarray'>
int32


array([0, 1, 2, 3, 4, 5])

### ndarry 형태(shape)와 차원
#### * 차원(Dimension,Rank) : 1,2,3차원, n차원, 첫 데이터까지의 대괄호의 갯수
#### * Shape : 차원의 요소의 수, 튜플 형식
####  1 차원 Shape : (x,)
####  2 차원 Shape : (x,y), 행렬(matrix)
####  3 차원 Shape : (x,y,z) , (면,행,열)
... 
####  n 차원 Shape : (x,y,z,....)

In [21]:
# 1 차원 배열의 Shape : (x,)
# np.arange(start,end+1,step)
a = np.arange(12)
print(a, type(a))
print(a.shape)    # (12,)
t = a.shape
print(type(t))    # <class 'tuple'>

a2 = np.arange(2,10)
print(a2,type(a2))
print(a2.shape)    # (8,)

a3 = np.arange(0,16,2)
print(a3,type(a3))
print(a3.shape)    # (8,)

# 2 차원 배열의 Shape : 행(row,가로,수직,axis=0) 과 열(column,세로,수평,axis=1) ==> 필수암기
# m = np.array([np.arange(3),np.arange(3)])
m = np.array([[0,1,2],
              [0,1,2]])
print(m)
print(m.shape)  # (2,3)
print(m.shape[0],m.shape[1])

# 3 차원 배열의 Shape : (면,행,열)
m = np.array([[[0,1,2],
               [3,4,5]],
              [[0,1,2],
               [3,4,5]]])
print(m,m.ndim)  # 3차원
print(m.shape)   # (2,2,3)
print(m.shape[0],m.shape[1],m.shape[2])

m2 = np.array([[[0, 1],
                [2, 3]],
               [[4, 5],
                [0, 1]],
               [[2, 3],
                [4, 5]]])
print(m2,m2.ndim) # 3차원 
print(m2.shape)   # (3,2,2)

m3 = np.array([[[0, 1],
                [2, 3],
                [4, 5]],
               [[0, 1],
                [2, 3],
                [4, 5]]])
print(m2.shape) # (2,3,2)

[ 0  1  2  3  4  5  6  7  8  9 10 11] <class 'numpy.ndarray'>
(12,)
<class 'tuple'>
[2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
(8,)
[ 0  2  4  6  8 10 12 14] <class 'numpy.ndarray'>
(8,)
[[0 1 2]
 [0 1 2]]
(2, 3)
2 3
[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]] 3
(2, 2, 3)
2 2 3
[[[0 1]
  [2 3]]

 [[4 5]
  [0 1]]

 [[2 3]
  [4 5]]] 3
(3, 2, 2)
(3, 2, 2)


### ndarray 타입(type)

### ndarray 타입(type)변환

In [20]:
# 배열의 데이터 타입 변환 : astype()
a1 = np.array(['1.234','3.123','4.4356','5','7'])
print(a1,a1.dtype)  # <U6 , <:리틀엔디언   U:유니코드  6:최대문자 6 byte

a2 = a1.astype('float32')
print(a2,a2.dtype)

# a3 = a1.astype('int32')  # ValueError
a3 = a2.astype('int32')    # OK!!
print(a3,a3.dtype)

['1.234' '3.123' '4.4356' '5' '7'] <U6
[1.234  3.123  4.4356 5.     7.    ] float32
[1 3 4 5 7] int32


### ndarray의 axis 축 

In [34]:
# 2 차원 배열의 Shape : 행(row,가로,수직,axis=0) 과 열(column,세로,수평,axis=1)

# axis 사용법
a = np.arange(12).reshape(3,4)
print(a,a.shape) 
print(a.sum())        # 배열 전체의 합

print(a.sum(axis=0))  # 행방향으로 합
print(a.sum(axis=1))  # 열방향으로 합

print(a.mean(axis=0))
print(a.mean(axis=1))


print(a.sum(axis=None))  # a.sum()와 동일한 결과
print(a.sum(axis=-1))    # a.sum(axis=1)  , -1은 마지막 축을 나타낸다

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
66
[12 15 18 21]
[ 6 22 38]
[4. 5. 6. 7.]
[1.5 5.5 9.5]
66
[ 6 22 38]


### ndarray를 편리하게 생성하기 - zeros, ones  

In [35]:
a = np.zeros((2, 3))  # 값이 모두 0인 배열 생성, 매개변수는 원하는 shape
print(a)

b = np.ones((3, 4))   # 값이 모두 1인 배열 생성
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### ndarray의 차원의 크기 변경 reshape()

In [23]:
m1 = np.arange(12)
print(m1,m1.shape) # (12,)

m2 = m1.reshape(12,1)
print(m2,m2.shape,type(m2))

m2 = m1.reshape(3,4)
print(m2,m2.shape)

m2 = m1.reshape(4,3)
print(m2,m2.shape)

m2 = m1.reshape(2,6)
print(m2,m2.shape)

m2 = m1.reshape(6,2)
print(m2,m2.shape)

m3 = m1.reshape(2,2,3)
print(m3,m3.shape)

m4 = m1.reshape(3,2,1,2)
print(m4,m4.shape)

m2 = np.arange(12).reshape(3,4)
print(m2,m2.shape)  # (3,4)

m2 = np.arange(18).reshape(2,-1)  
print(m2,m2.shape)  # (2,9)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]] (12, 1) <class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] (4, 3)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] (6, 2)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)
[[[[ 0  1]]

  [[ 2  3]]]


 [[[ 4  5]]

  [[ 6  7]]]


 [[[ 8  9]]

  [[10 11]]]] (3, 2, 1, 2)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]] (2, 9)


### ndarray의 데이터 세트 선택하기 - 인덱싱(indexing), 슬라이싱(slicing)

#### 단일 값 추출 - 1차원 ndarray

In [24]:
# 1차원 배열의 인덱싱과 슬라이싱 : list와 동일한 방법
d = np.arange(12)
print(d,d.shape)

print(d[0],d[1],d[2],d[-1],d[-2])
print(d[2:8],d[0:1],d[:],d[:-1])
print(d[::2],d[::-1])

d[0] = 10   # list 처럼 요소 변경이 가능
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
0 1 2 11 10


#### 단일 값 추출 - 2차원 ndarray

In [25]:
# 2차원 배열의 인덱싱과 슬라이싱 
# data[행,열]
d = np.arange(12).reshape(3,4)
print(d,d.shape)

# 인덱싱
print(d[0][0]) # old style, 0
print(d[0,0])  # 0
print(d[2,1])  # 9

# 슬라이싱
print(d[0])    # [0 1 2 3]
print(d[0,:])  # [0 1 2 3]

print(d[:,:-1])   # (3,3), 마지막 열을 제외
print(d[::2,::2]) # (2,2)

d[0] = 20         # 0번 행의 모든 요소를 20으로 변경
print(d)
d[:,:] = -1       # 전체 요소를 한번에 변경할 수 있다
print(d)

d[::2,::3] = 30
print(d[::2,::3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
0
0
9
[0 1 2 3]
[0 1 2 3]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 0  2]
 [ 8 10]]
[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]
[[30 30]
 [30 30]]


### 팬시 인덱싱 
+ 리스트나 배열로 임의의 집합을 지정하여 인덱싱, (원하는대로 인덱싱)

### 팬시 인덱싱 - 1차원 ndarray

In [27]:
# 1차원 배열의 팬시 인덱싱
a = np.arange(1,7)
print(a,a.shape)
print(a[[1,3,5,2]])
print(a[[0,-1,-3,-2]])

[1 2 3 4 5 6] (6,)
[2 4 6 3]
[1 6 4 5]


### 팬시 인덱싱 - 2차원 ndarray

In [28]:
# 2차원 배열의 팬시 인덱싱
# data[[행인덱싱 리스트],[열인덱싱 리스트]]
a = np.arange(10,100,10).reshape(3,3)
print(a,a.shape)

print(a[[0,2],[0,1]]) # 행과 열이 서로 match, a[0,0]과 a[2,1] 값으로 배열 반환
                      # 행과 열의 갯수가 같아야함
print(a[[0,2],:2])

print(a[0,0],a[2,1])

[[10 20 30]
 [40 50 60]
 [70 80 90]] (3, 3)
[10 80]
[[10 20]
 [70 80]]
10 80


### 불린 인덱싱 
+ 조건식을 사용한 인덱싱, 조건 검색필터를 사용한 추출(매우 중요)


In [26]:
a = np.array([1,2,3,4,5,6])
print(a)

print(a > 2)   # [False False  True  True  True  True]
print(a[a > 2]) # 배열 a에 2보다 큰 요소들을 추출
print(a[[False,False,True,True,True,True]])

boolean_index = np.array([True,False,True,False,True,True]) # 리스트를 사용해도 가능
print(boolean_index)
print(a[boolean_index])

print(a[a != 3])
print(a[(a > 2) & (a < 6)])
print(a[a % 2 == 0])
print(a[a < a.mean()])  # 배열  a에서 평균 보다 작은 값만 추출

# print(a[True])
# print(a[False])

[1 2 3 4 5 6]
[False False  True  True  True  True]
[3 4 5 6]
[3 4 5 6]
[ True False  True False  True  True]
[1 3 5 6]
[1 2 4 5 6]
[3 4 5]
[2 4 6]
[1 2 3]


### 배열의 정렬 - sort(), argsort()

In [30]:
# sort()함수
a = np.array([9,2,8,3,1,4,5,6])
print(a,a.shape)

print(np.sort(a)) # 오름차순, 원본 변경 없음, sort된 결과를 반환
print(a)
print('-'*30)
a.sort()          # 오름차순, 원본 변경 
print(a)

print(np.sort(a)[::-1])  # 내림 차순

[9 2 8 3 1 4 5 6] (8,)
[1 2 3 4 5 6 8 9]
[9 2 8 3 1 4 5 6]
------------------------------
[1 2 3 4 5 6 8 9]
[9 8 6 5 4 3 2 1]


In [31]:
# argsort() 함수 : sort된 후 해당값의 인덱스(원본 기준)를 배열로 반환
a = np.array([9,2,8,3,1,4,5,6])
print(a,a.shape)

sort_index = np.argsort(a)
print(sort_index)

[9 2 8 3 1 4 5 6] (8,)
[4 1 3 5 6 7 2 0]


### 선형대수 연산 - 행렬 내적
+ np.dot(A,B)

In [32]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
print(A)   # (2,3)
print(B)   # (3,2)

# print(A * B) # ValueError , shape 다르고 1도 아님, 요소간의 곱셈

dot_product = np.dot(A,B)
print(dot_product)


[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]


### 선행대수 연산 - 전치 행렬
+ np.transpose(A)

In [33]:
# transpose() : 전치 행렬, 행과 열을 서로 맞바꾸는 함수
t = d.transpose()   # (3,4)  ---> (4,3)
print(t,t.shape)
print(d.T)   # transpose()와 동일한 결과

[[30 -1 30]
 [-1 -1 -1]
 [-1 -1 -1]
 [30 -1 30]] (4, 3)
[[30 -1 30]
 [-1 -1 -1]
 [-1 -1 -1]
 [30 -1 30]]


# Pandas 

### Pandas의 장점 
+ csv, 엑셀, Database, Json 등 다양한 소스에서 데이터를 가져오고 해당 형식으로 데이터를 내보낼 수 있는 입출력 기능 
+ 데이터 삽입, 삭제, 병합, 결합, 슬라이싱, 인덱싱 등 데이터를 필요한 대로 조작할 수 있음
+ 누락 데이터 처리 용이
+ 통계분석이나 머신러닝 분석 가능하도록 연구모델 설정 가능 
+ 데이터분석 패키지와 쉽게 연동되어 사용가능
+ 빠른 속도로 데이터 처리 가능 

In [36]:
import pandas as pd 

### 판다스의 주요 구성 요소 - DataFrame,Series,index 
(1) DataFrame 객체 : 2차원 배열, 서로 다른 자료형을 사용할 수 있다,행(인스턴스),열(컬럼,피쳐(feature))

(2) Series 객체 : 1차원 배열, 1차원 ndarray 와 호환¶

In [38]:
# pip install pandas
import pandas as pd
import numpy as np

# 2차원 리스트,배열을 사용하여 생성
df = pd.DataFrame([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(type(df))
# print(df)
df

# 사전(dict) 을 사용하여 생성
score_table = { '성명': ['홍길동','김철수','김영희','나','너'],
                '국어': [50.,60,70,80,90],
                '영어': [10,20,30,40,50],
                '수학': [70,80,90,30,20]}
# print(score_table,type(score_table))

df = pd.DataFrame(score_table)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


성명    국어  영어  수학
0  홍길동  50.0  10  70
1  김철수  60.0  20  80
2  김영희  70.0  30  90
3    나  80.0  40  30
4    너  90.0  50  20

In [39]:
# dictionary를 이용해 만들기
dic = {'a':1, 'b':3, 'c':5}
s = pd.Series(dic)
print(s)
print(s['b']) #indexing


print(s.values)
print(s.index)

s = pd.Series([1,3,5,7,9], index=['LGT','DOO','HWE','LOT','SKW'])
#print(s)
#print(s['LOT'])
print(s[:'LOT']) # 슬라이싱에서 어디까지 나오는지 주목

a    1
b    3
c    5
dtype: int64
3
[1 3 5]
Index(['a', 'b', 'c'], dtype='object')
LGT    1
DOO    3
HWE    5
LOT    7
dtype: int64


### 데이터 셀렉션 및 필터링

### 데이터 셀렉션 및 필터링 - ix,loc, iloc
+ ix[] - 명칭 기반과 위치 기반 인덱싱을 함께 제공 
+ loc[] - 명칭 기반 인덱싱 
+ iloc[] - 위치 기반 인덱싱 

In [46]:
df = pd.read_csv('WHO_first9cols.csv')
df
# NaN : Not a Number, 결측치

Country  CountryID  Continent  Adolescent fertility rate (%)  \
0           Afghanistan          1          1                          151.0   
1               Albania          2          2                           27.0   
2               Algeria          3          3                            6.0   
3               Andorra          4          2                            NaN   
4                Angola          5          3                          146.0   
..                  ...        ...        ...                            ...   
197             Vietnam        198          6                           25.0   
198  West Bank and Gaza        199          1                            NaN   
199               Yemen        200          1                           83.0   
200              Zambia        201          3                          161.0   
201            Zimbabwe        202          3                          101.0   

     Adult literacy rate (%)  \
0                       28.0   
1                       98.7   
2                       69.9   
3                        NaN   
4                       67.4   
..                       ...   
197                     90.3   
198                      NaN   
199                     54.1   
200                     68.0   
201                     89.5   

     Gross national income per capita (PPP international $)  \
0                                                  NaN        
1                                               6000.0        
2                                               5940.0        
3                                                  NaN        
4                                               3890.0        
..                                                 ...        
197                                             2310.0        
198                                                NaN        
199                                             2090.0        
200                                             1140.0        
201                                                NaN        

     Net primary school enrolment ratio female (%)  \
0                                              NaN   
1                                             93.0   
2                                             94.0   
3                                             83.0   
4                                             49.0   
..                                             ...   
197                                           91.0   
198                                            NaN   
199                                           65.0   
200                                           94.0   
201                                           88.0   

     Net primary school enrolment ratio male (%)  \
0                                            NaN   
1                                           94.0   
2                                           96.0   
3                                           83.0   
4                                           51.0   
..                                           ...   
197                                         96.0   
198                                          NaN   
199                                         85.0   
200                                         90.0   
201                                         87.0   

     Population (in thousands) total  
0                            26088.0  
1                             3172.0  
2                            33351.0  
3                               74.0  
4                            16557.0  
..                               ...  
197                          86206.0  
198                              NaN  
199                          21732.0  
200                          11696.0  
201                          13228.0  

[202 rows x 9 columns]

In [47]:
# df.loc[]  : 컬럼인덱스를 컬럼이름으로 사용
df.loc[3,'Country']   # 3번 행, 0번 컬럼
df.loc[:3,'Country']  # start:end, end - 1 까지가 아님(주의)
df.loc[:3,['Country','CountryID','Continent']]

Country  CountryID  Continent
0  Afghanistan          1          1
1      Albania          2          2
2      Algeria          3          3
3      Andorra          4          2

In [48]:
# df.iloc[] : 컬럼인덱스를 int형으로 사용, 자주사용됨!!
df.iloc[3,0]
df.iloc[:3,0:3] # start: end + 1
df.iloc[:3,[0,2,4]]

df.iloc[:,:-1]  # 마지막 컬럼을 제외, X(독립변수) 추출
df.iloc[:,-1]   # 마지막 컬럼만 추출, Y(종속변수) 추출

# 스칼라 요소값의 변경
df.iloc[3,0] = 'Dorra'    # 'Andorra' --> 'Dorra'
df.iloc[3,0] = 'Andorra'  # 'Dorra'   --> 'Andorra' 

# -1 사용 가능
df.iloc[-1,0]
df.iloc[0,-1]

26088.0

### 데이터 프레임 함수들 

In [49]:
df.head()

Country  CountryID  Continent  Adolescent fertility rate (%)  \
0  Afghanistan          1          1                          151.0   
1      Albania          2          2                           27.0   
2      Algeria          3          3                            6.0   
3      Andorra          4          2                            NaN   
4       Angola          5          3                          146.0   

   Adult literacy rate (%)  \
0                     28.0   
1                     98.7   
2                     69.9   
3                      NaN   
4                     67.4   

   Gross national income per capita (PPP international $)  \
0                                                NaN        
1                                             6000.0        
2                                             5940.0        
3                                                NaN        
4                                             3890.0        

   Net primary school enrolment ratio female (%)  \
0                                            NaN   
1                                           93.0   
2                                           94.0   
3                                           83.0   
4                                           49.0   

   Net primary school enrolment ratio male (%)  \
0                                          NaN   
1                                         94.0   
2                                         96.0   
3                                         83.0   
4                                         51.0   

   Population (in thousands) total  
0                          26088.0  
1                           3172.0  
2                          33351.0  
3                             74.0  
4                          16557.0

In [50]:
df.tail()

Country  CountryID  Continent  Adolescent fertility rate (%)  \
197             Vietnam        198          6                           25.0   
198  West Bank and Gaza        199          1                            NaN   
199               Yemen        200          1                           83.0   
200              Zambia        201          3                          161.0   
201            Zimbabwe        202          3                          101.0   

     Adult literacy rate (%)  \
197                     90.3   
198                      NaN   
199                     54.1   
200                     68.0   
201                     89.5   

     Gross national income per capita (PPP international $)  \
197                                             2310.0        
198                                                NaN        
199                                             2090.0        
200                                             1140.0        
201                                                NaN        

     Net primary school enrolment ratio female (%)  \
197                                           91.0   
198                                            NaN   
199                                           65.0   
200                                           94.0   
201                                           88.0   

     Net primary school enrolment ratio male (%)  \
197                                         96.0   
198                                          NaN   
199                                         85.0   
200                                         90.0   
201                                         87.0   

     Population (in thousands) total  
197                          86206.0  
198                              NaN  
199                          21732.0  
200                          11696.0  
201                          13228.0

In [51]:
df.shape

(202, 9)

In [52]:
df.columns.tolist()

['Country',
 'CountryID',
 'Continent',
 'Adolescent fertility rate (%)',
 'Adult literacy rate (%)',
 'Gross national income per capita (PPP international $)',
 'Net primary school enrolment ratio female (%)',
 'Net primary school enrolment ratio male (%)',
 'Population (in thousands) total']

In [53]:
df.describe()

CountryID   Continent  Adolescent fertility rate (%)  \
count  202.000000  202.000000                     177.000000   
mean   101.500000    3.579208                      59.457627   
std     58.456537    1.808263                      49.105286   
min      1.000000    1.000000                       0.000000   
25%     51.250000    2.000000                      19.000000   
50%    101.500000    3.000000                      46.000000   
75%    151.750000    5.000000                      91.000000   
max    202.000000    7.000000                     199.000000   

       Adult literacy rate (%)  \
count               131.000000   
mean                 78.871756   
std                  20.415760   
min                  23.600000   
25%                  68.400000   
50%                  86.500000   
75%                  95.300000   
max                  99.800000   

       Gross national income per capita (PPP international $)  \
count                                         178.000000        
mean                                        11250.112360        
std                                         12586.753417        
min                                           260.000000        
25%                                          2112.500000        
50%                                          6175.000000        
75%                                         14502.500000        
max                                         60870.000000        

       Net primary school enrolment ratio female (%)  \
count                                     179.000000   
mean                                       84.033520   
std                                        17.788047   
min                                         6.000000   
25%                                        79.000000   
50%                                        90.000000   
75%                                        96.000000   
max                                       100.000000   

       Net primary school enrolment ratio male (%)  \
count                                   179.000000   
mean                                     85.698324   
std                                      15.451212   
min                                      11.000000   
25%                                      79.500000   
50%                                      90.000000   
75%                                      96.000000   
max                                     100.000000   

       Population (in thousands) total  
count                     1.890000e+02  
mean                      3.409964e+04  
std                       1.318377e+05  
min                       2.000000e+00  
25%                       1.328000e+03  
50%                       6.640000e+03  
75%                       2.097100e+04  
max                       1.328474e+06

In [54]:
df.max()

Country                                                      Zimbabwe
CountryID                                                         202
Continent                                                           7
Adolescent fertility rate (%)                                     199
Adult literacy rate (%)                                          99.8
Gross national income per capita (PPP international $)          60870
Net primary school enrolment ratio female (%)                     100
Net primary school enrolment ratio male (%)                       100
Population (in thousands) total                           1.32847e+06
dtype: object

In [58]:
df['Population (in thousands) total'].max()

1328474.0

In [56]:
df['Adult literacy rate (%)'].mean()

78.87175572519084

In [60]:
df['Gross national income per capita (PPP international $)'].argmax()

103

In [61]:
df['Continent'].value_counts()

2    51
3    48
6    35
5    31
1    21
7     9
4     7
Name: Continent, dtype: int64

### 정렬(Sorting)

In [64]:
df.sort_values('CountryID').head()

Country  CountryID  Continent  Adolescent fertility rate (%)  \
0  Afghanistan          1          1                          151.0   
1      Albania          2          2                           27.0   
2      Algeria          3          3                            6.0   
3      Andorra          4          2                            NaN   
4       Angola          5          3                          146.0   

   Adult literacy rate (%)  \
0                     28.0   
1                     98.7   
2                     69.9   
3                      NaN   
4                     67.4   

   Gross national income per capita (PPP international $)  \
0                                                NaN        
1                                             6000.0        
2                                             5940.0        
3                                                NaN        
4                                             3890.0        

   Net primary school enrolment ratio female (%)  \
0                                            NaN   
1                                           93.0   
2                                           94.0   
3                                           83.0   
4                                           49.0   

   Net primary school enrolment ratio male (%)  \
0                                          NaN   
1                                         94.0   
2                                         96.0   
3                                         83.0   
4                                         51.0   

   Population (in thousands) total  
0                          26088.0  
1                           3172.0  
2                          33351.0  
3                             74.0  
4                          16557.0

### 조건에 따라 행 추출

In [65]:
print(type(df['Adolescent fertility rate (%)'] > 70)) # True/False 시리즈로 반환되는지 확인
(df['Adolescent fertility rate (%)'] > 70).head() # 시리즈의 앞부분을 확인

<class 'pandas.core.series.Series'>


0     True
1    False
2    False
3    False
4     True
Name: Adolescent fertility rate (%), dtype: bool

In [67]:
df[df['Adolescent fertility rate (%)'] > 70].head()

Country  CountryID  Continent  Adolescent fertility rate (%)  \
0   Afghanistan          1          1                          151.0   
4        Angola          5          3                          146.0   
13   Bangladesh         14          7                          135.0   
17       Belize         18          5                           90.0   
18        Benin         19          3                          108.0   

    Adult literacy rate (%)  \
0                      28.0   
4                      67.4   
13                     47.5   
17                     70.3   
18                     34.7   

    Gross national income per capita (PPP international $)  \
0                                                 NaN        
4                                              3890.0        
13                                             1230.0        
17                                             7080.0        
18                                             1250.0        

    Net primary school enrolment ratio female (%)  \
0                                             NaN   
4                                            49.0   
13                                           90.0   
17                                           97.0   
18                                           73.0   

    Net primary school enrolment ratio male (%)  \
0                                           NaN   
4                                          51.0   
13                                         87.0   
17                                         97.0   
18                                         87.0   

    Population (in thousands) total  
0                           26088.0  
4                           16557.0  
13                         155991.0  
17                            282.0  
18                           8760.0

In [70]:
df[(df['Adolescent fertility rate (%)'] > 70) & (df['Adult literacy rate (%)'] < 30)]

Country  CountryID  Continent  Adolescent fertility rate (%)  \
0     Afghanistan          1          1                          151.0   
27   Burkina Faso         28          3                          131.0   
34           Chad         35          3                          193.0   
71         Guinea         72          3                          153.0   
110          Mali        111          3                          192.0   
132         Niger        133          3                          199.0   

     Adult literacy rate (%)  \
0                       28.0   
27                      23.6   
34                      25.7   
71                      29.5   
110                     24.0   
132                     28.7   

     Gross national income per capita (PPP international $)  \
0                                                  NaN        
27                                              1130.0        
34                                              1170.0        
71                                              1130.0        
110                                             1000.0        
132                                              630.0        

     Net primary school enrolment ratio female (%)  \
0                                              NaN   
27                                            42.0   
34                                            49.0   
71                                            66.0   
110                                           54.0   
132                                           37.0   

     Net primary school enrolment ratio male (%)  \
0                                            NaN   
27                                          52.0   
34                                          71.0   
71                                          77.0   
110                                         67.0   
132                                         50.0   

     Population (in thousands) total  
0                            26088.0  
27                           14359.0  
34                           10468.0  
71                            9181.0  
110                          11968.0  
132                          13737.0

### 그룹화(Grouping)

In [71]:
df.groupby('Continent')['Adult literacy rate (%)'].mean().head()

Continent
1    76.900000
2    97.911538
3    61.690476
4    91.600000
5    87.940909
Name: Adult literacy rate (%), dtype: float64

### 데이터 클리닝 

In [72]:
df.isnull().sum()

Country                                                    0
CountryID                                                  0
Continent                                                  0
Adolescent fertility rate (%)                             25
Adult literacy rate (%)                                   71
Gross national income per capita (PPP international $)    24
Net primary school enrolment ratio female (%)             23
Net primary school enrolment ratio male (%)               23
Population (in thousands) total                           13
dtype: int64

+ dropna() - 결측치가 있는 모든 행을 없앤다.
+ fillna() - 결측치를 정해진 값으로 바꾼다.

In [74]:
df.fillna(0)

Country  CountryID  Continent  Adolescent fertility rate (%)  \
0           Afghanistan          1          1                          151.0   
1               Albania          2          2                           27.0   
2               Algeria          3          3                            6.0   
3               Andorra          4          2                            0.0   
4                Angola          5          3                          146.0   
..                  ...        ...        ...                            ...   
197             Vietnam        198          6                           25.0   
198  West Bank and Gaza        199          1                            0.0   
199               Yemen        200          1                           83.0   
200              Zambia        201          3                          161.0   
201            Zimbabwe        202          3                          101.0   

     Adult literacy rate (%)  \
0                       28.0   
1                       98.7   
2                       69.9   
3                        0.0   
4                       67.4   
..                       ...   
197                     90.3   
198                      0.0   
199                     54.1   
200                     68.0   
201                     89.5   

     Gross national income per capita (PPP international $)  \
0                                                  0.0        
1                                               6000.0        
2                                               5940.0        
3                                                  0.0        
4                                               3890.0        
..                                                 ...        
197                                             2310.0        
198                                                0.0        
199                                             2090.0        
200                                             1140.0        
201                                                0.0        

     Net primary school enrolment ratio female (%)  \
0                                              0.0   
1                                             93.0   
2                                             94.0   
3                                             83.0   
4                                             49.0   
..                                             ...   
197                                           91.0   
198                                            0.0   
199                                           65.0   
200                                           94.0   
201                                           88.0   

     Net primary school enrolment ratio male (%)  \
0                                            0.0   
1                                           94.0   
2                                           96.0   
3                                           83.0   
4                                           51.0   
..                                           ...   
197                                         96.0   
198                                          0.0   
199                                         85.0   
200                                         90.0   
201                                         87.0   

     Population (in thousands) total  
0                            26088.0  
1                             3172.0  
2                            33351.0  
3                               74.0  
4                            16557.0  
..                               ...  
197                          86206.0  
198                              0.0  
199                          21732.0  
200                          11696.0  
201                          13228.0  

[202 rows x 9 columns]

In [75]:
df.dropna()

Country  CountryID  Continent  Adolescent fertility rate (%)  \
1      Albania          2          2                           27.0   
2      Algeria          3          3                            6.0   
4       Angola          5          3                          146.0   
6    Argentina          7          5                           62.0   
7      Armenia          8          2                           30.0   
..         ...        ...        ...                            ...   
195    Vanuatu        196          6                           92.0   
196  Venezuela        197          5                           81.0   
197    Vietnam        198          6                           25.0   
199      Yemen        200          1                           83.0   
200     Zambia        201          3                          161.0   

     Adult literacy rate (%)  \
1                       98.7   
2                       69.9   
4                       67.4   
6                       97.2   
7                       99.4   
..                       ...   
195                     75.5   
196                     93.0   
197                     90.3   
199                     54.1   
200                     68.0   

     Gross national income per capita (PPP international $)  \
1                                               6000.0        
2                                               5940.0        
4                                               3890.0        
6                                              11670.0        
7                                               4950.0        
..                                                 ...        
195                                             3480.0        
196                                            10970.0        
197                                             2310.0        
199                                             2090.0        
200                                             1140.0        

     Net primary school enrolment ratio female (%)  \
1                                             93.0   
2                                             94.0   
4                                             49.0   
6                                             98.0   
7                                             84.0   
..                                             ...   
195                                           86.0   
196                                           91.0   
197                                           91.0   
199                                           65.0   
200                                           94.0   

     Net primary school enrolment ratio male (%)  \
1                                           94.0   
2                                           96.0   
4                                           51.0   
6                                           99.0   
7                                           80.0   
..                                           ...   
195                                         88.0   
196                                         91.0   
197                                         96.0   
199                                         85.0   
200                                         90.0   

     Population (in thousands) total  
1                             3172.0  
2                            33351.0  
4                            16557.0  
6                            39134.0  
7                             3010.0  
..                               ...  
195                            221.0  
196                          27191.0  
197                          86206.0  
199                          21732.0  
200                          11696.0  

[118 rows x 9 columns]

### CSV 파일로 데이터프레임 저장

In [76]:
df.fillna(0).to_csv('test.csv')
df1 = pd.read_csv('test.csv')
df1

Unnamed: 0             Country  CountryID  Continent  \
0             0         Afghanistan          1          1   
1             1             Albania          2          2   
2             2             Algeria          3          3   
3             3             Andorra          4          2   
4             4              Angola          5          3   
..          ...                 ...        ...        ...   
197         197             Vietnam        198          6   
198         198  West Bank and Gaza        199          1   
199         199               Yemen        200          1   
200         200              Zambia        201          3   
201         201            Zimbabwe        202          3   

     Adolescent fertility rate (%)  Adult literacy rate (%)  \
0                            151.0                     28.0   
1                             27.0                     98.7   
2                              6.0                     69.9   
3                              0.0                      0.0   
4                            146.0                     67.4   
..                             ...                      ...   
197                           25.0                     90.3   
198                            0.0                      0.0   
199                           83.0                     54.1   
200                          161.0                     68.0   
201                          101.0                     89.5   

     Gross national income per capita (PPP international $)  \
0                                                  0.0        
1                                               6000.0        
2                                               5940.0        
3                                                  0.0        
4                                               3890.0        
..                                                 ...        
197                                             2310.0        
198                                                0.0        
199                                             2090.0        
200                                             1140.0        
201                                                0.0        

     Net primary school enrolment ratio female (%)  \
0                                              0.0   
1                                             93.0   
2                                             94.0   
3                                             83.0   
4                                             49.0   
..                                             ...   
197                                           91.0   
198                                            0.0   
199                                           65.0   
200                                           94.0   
201                                           88.0   

     Net primary school enrolment ratio male (%)  \
0                                            0.0   
1                                           94.0   
2                                           96.0   
3                                           83.0   
4                                           51.0   
..                                           ...   
197                                         96.0   
198                                          0.0   
199                                         85.0   
200                                         90.0   
201                                         87.0   

     Population (in thousands) total  
0                            26088.0  
1                             3172.0  
2                            33351.0  
3                               74.0  
4                            16557.0  
..                               ...  
197                          86206.0  
198                              0.0  
199                          21732.0  
200                          11696.0  
201                          13228.0  

[202 rows x 10 