## Numpy 기초연습문제

In [1]:
import numpy as np  # numpy 호출 

### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [2]:
a = np.zeros((3,4)) # 행 3, 열 4 일 ndarray 생성 
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

In [3]:
for i in range(a.shape[0]):    # a.shape[0] = 3 - > 0,1,2
    for j in range(a.shape[1]): # a.shape[1] = 4 -> 0,1,2,3
        a[i, j] = i*4 + j + 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [4]:
num = 1
for i in range(a.shape[0]): # a.shape[0] = 3 - > 0,1,2
    for j in range(a.shape[1]): # a.shape[1] = 4 -> 0,1,2,3
        a[i, j] =  num
        num += 1 # num에 1씩 증가 
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [5]:
a[1,2] # 두번째 행, 3번째 열 -> 1,2

7.0

### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

In [6]:
a.shape # shape (3,4)

(3, 4)

In [7]:
a[[1], :] # 두번째 행 인덱싱 => [1]-> 두번째행, ':' -> 모두 

array([[5., 6., 7., 8.]])

### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

In [18]:
a[:,[1, 2]] # 둘째 열, 셋째 열 인덱싱 => ':''-> 모두, [1,2]->둘째,셋째 열  

array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])

### 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

In [9]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result
# a.shape[0] = 3 - > 0,1,2, a.shape[1] = 4 -> 0,1,2,3 에서 6보다 작은 값을 ndarray로 만들어 
# result에 저장 

array([1., 2., 3., 4., 5., 6.])

In [10]:
a[a <= 6]  # 6보다 작거나 같은 값 불린 인덱싱

array([1., 2., 3., 4., 5., 6.])

### 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [11]:
b = np.random.random((3, 4)) # 3행 4열인 값이 0~1 사이 무작위 값인 ndarray
b

array([[0.8830714 , 0.34515759, 0.5794572 , 0.18232567],
       [0.82323393, 0.15405876, 0.72081452, 0.44216423],
       [0.78673679, 0.99644265, 0.26238819, 0.4081762 ]])

### 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [12]:
c = a * b # a * b의 곱 c에 저장
c

array([[0.8830714 , 0.69031517, 1.7383716 , 0.7293027 ],
       [4.11616967, 0.92435255, 5.04570167, 3.53731385],
       [7.08063107, 9.96442652, 2.88627009, 4.89811446]])

### 9. b의 전치행렬을 구하여 d에 저장하시오.

In [13]:
d = b.T  # b의 전치행렬 d에 저장 3,4 -> 4,3
d


array([[0.8830714 , 0.82323393, 0.78673679],
       [0.34515759, 0.15405876, 0.99644265],
       [0.5794572 , 0.72081452, 0.26238819],
       [0.18232567, 0.44216423, 0.4081762 ]])

In [14]:
d.shape # shape 확인 


(4, 3)

### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [15]:
print(a.shape, d.shape) # a,d 각각의 shape 출력 

(3, 4) (4, 3)


### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [16]:
e = a.dot(d) # numpy 곱 a에 d를 곱하여 e에 저장 
e

array([[ 4.04106087,  5.06245195,  5.19949148],
       [12.00110832, 13.62353773, 15.01446681],
       [19.96115576, 22.18462352, 24.82944214]])

### 12. e에 대하여 각 열의 합을 계산하시오.

In [17]:
np.sum(e, axis=1)  # axis=1은 각 열을 의미, e의 각 열의 합을 계산 

array([14.3030043 , 40.63911286, 66.97522142])